services:
  api:
    build: .
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongo:27017/expense_tracker
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
